### ISSUE TITLE
Add new payment method

### ISSUE THREAD

**Issue by ramoncodit** [GoteoFoundation/goteo#110]
Good evening,
I'm looking for to add a new Payment method.
As far as I could see, Goteo platform is using Omnipay lib, who allows to interact with a wide variety of payment platforms, with Paypal among that.

In config/settings.yml I can see payment gateway settings, by default paypal:
```
# Payment methods, must be registered as classes implementing Goteo\Payment\Method\PaymentMethodInterface
payments:
    # Paypal
    paypal:
        active: true
        testMode:  true # set to false to real checkouts
        username: paypal@example.com
        password: paypal-password
        signature: PAYPAL-Signature
        appId: PAYPAL-APP-ID
```

As it can be read, there's a comment line where appoints to add new payment form:
```
# Additional custom payment methods should be added here
```

I have checked that Omnipay allows Stripe gateway and has its methods into vendor/omnipay folder.
So, I tried to add Stripe payment method. Here are my steps:

1. Added code block on config/settings.yml, let's say:
```
    stripe:
        active: true
        testMode:  true # set to false to real checkouts
        username: stripe@example.com
        password: stripe-password
        signature: STRIPE-Signature
        appId: STRIPE-APP-ID
```

In order to continue, I realised that all payment steps are controlled into :
- src/Goteo/Controller/InvestController.php

In other hand, I found a PayPal library file on:
- src/Goteo/Library/Paypal.php

And a "Payment lib" who works as a payment library methods, I suppose...
- src/Goteo/Payment/Payment.php

I suppose I must implement de Stripe library, something as create a file like follows:
- src/Goteo/Library/Stripe.php
to implement specific methods to interact with Stripe API.
And this other one too:
- src/Goteo/Payment/Method/StripePaymentMethod.php

But what worries me is that I have seen that in project config, in step 6, appears a check to allow to pay it with paypal method. That option is saved into database table project_account, with specific fields: 'paypal' & 'paypal_owner', next to fields 'bank' & 'bank_owner'
So, my question is, to add Stripe payment method, it has to been added new fields like 'stripe' & 'stripe_owner' in that table ? 
In that way, to add new payment method, means that are straight "hard-linked" to project definition ?

Or maybe I'm complicating the matter more than I should... ?

Thanks in advance for to have read till here.
Greetings

**Comment by microstudi** [comment]
Hi, I'm happy that someone is going to implement a new Payment Method.

First, forget about the Library/Paypal.php file, that's used in the legacy system and we didn't remove it yet because i may break things with the old admin.

The key is to implement [`Goteo\Payment\Method\PaymentMethodInterface`](https://github.com/GoteoFoundation/goteo/blob/devel/src/Goteo/Payment/Method/PaymentMethodInterface.php) interface and register the class as is done in the [`Config.php`](https://github.com/GoteoFoundation/goteo/blob/devel/src/Goteo/Application/Config.php#L227) file. After that, it can be included in the settings file.

In the core code we have [3 payment implementations](https://github.com/GoteoFoundation/goteo/tree/devel/src/Goteo/Payment/Method) Cash, Paypal and Pool. 

There's a 4th implementation in the [Goteo-Dev plugin](https://github.com/GoteoFoundation/goteo/blob/devel/extend/goteo-dev/src/Goteodev/Payment/DummyPaymentMethod.php) that registers itself if you activate the plugin in its [start.php file](https://github.com/GoteoFoundation/goteo/blob/devel/extend/goteo-dev/start.php#L48).

if you study these cases you shouldn't have problems to implement a new Payment method. And I don't think you'll need to create any `Library/Stripe.php` additional class, adding the Omnipay Stripe class in [composer.json](https://github.com/GoteoFoundation/goteo/blob/devel/composer.json#L58) `omnipay/stripe` should be enough. 

Check the documentation of Omnipay regarding [Stripe](https://github.com/thephpleague/omnipay-stripe).

About the paypal fields: There are not related to the payment, all the payment info is in the `invest` table, those fields are for the project owners (we require them to have a paypal account if they want to accept and receive money that way). So, don't bother about them.

Feel free to start coding and show me your progress, I'll give you my comments, but please use the latests versions of the Goteo source code.

Good luck!

**Comment by ramoncodit** [comment]
Hi!
first of all, thanks in advance for your quick response! 
I'll start working as you have suggested me.

Thanks!

**Comment by ramoncodit** [comment]
Hi @microstudi ,
to start with new payment method, I've thought maybe it's better to focus it as a plugin, like dummy payment method.
So I've followed next steps:
1. I've created files into 'extend' folder, following the plugin steps on docs:
- http://goteofoundation.github.io/goteo/docs/developers/extend.html
2. I've added Stripe apiKey on config/settings.yml
```
payments:
    ...
    # Additional custom payment methods should be added here
    stripe:
        active: true
        apiKey: STRIPE-API-KEY
```
3. I've added plugin activation on config/settings.yml
```
plugins:
    payment-stripe:
        active: true # plugin should be active=true to be loaded
```
4. I've added dependencies in composer.json
```
    "require": {
            ...
            "omnipay/stripe": "~2.0",
     }
```

At that point, I've needed to add a new step, that's to show a pop-up from Stripe site to ask customer credit card data to make the Stripe purchase() request.
So I've followed Stripe's site steps to show form: 
- https://stripe.com/docs/checkout#integration-simple
into payment_method template, overriding it into plugin folder:
- extend/payment-stripe/Resources/templates/responsive/invest/payment_method.php

Now, when I submit that form, it wil be catched on paymentFormAction() method from InvestController.php

So, my question here is, is it possible to override an existing controller, in this case, InvestController.php, like we do with templates, only creating the same file name and paths into plugin folder, as it follows:
- extend/payment-stripe/src/Goteo/Controller/InvestController.php

or it's better to add the specific Stripe response data treatment code on general InvestController?
- src/Goteo/Controller/InvestController.php 

And if it's possible to override a controller, does it is possible to override only one method? Or when overriding, we must copy-implement all original controller code ?

I don't want to mess up all...

Thanks in advance.
Greetings
