### ISSUE TITLE
Exact location: -Unlocated- Issue

### ISSUE THREAD

**Issue by marshadshaheen** [GoteoFoundation/goteo#68]
When I type any location, there is no suggestion list as it appears in goteo.org
after saving, when I visit the page http://myserver:8081/dashboard/settings/profile , the exact location is 'Unlocated'. I tried even Barcelona but there is error that its not located

on second step, there is no enabled option or map when it prompts for drag and drop page to locate the exact location

However no error message
please help

**Comment by microstudi** [comment]
You might need to configurate properly the settings.yml
This part:
```yaml
geolocation:
    # Path to maxmind databases, you need to download (and keep updated) either the free o comercial
    # databases from maxmind. Check this for more info: https://dev.maxmind.com/geoip/geoipupdate/
    # relative paths are allowed (ie: you can save your maxmind databases into config/resources/maxmind if you want)
    maxmind:
        cities: /usr/share/GeoIP/GeoLite2-City.mmdb
    google_maps_key: 'your-google-maps-key'
```
